# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    data:
        mongodb:
            uri: ${vcap.services.mongodb.credentials.uri}
    mail:
        host: ${vcap.services.email.credentials.hostname}
        port: 587
        username: ${vcap.services.email.credentials.username}
        password: ${vcap.services.email.credentials.password}
    thymeleaf:
        cache: true
        
management:
  metrics:
    export:
      cloudwatch:
        namespace: metadatamanagement-prod
        batch-size: 20

# ===================================================================
# Properties specific to our application
# ===================================================================

metadatamanagement:
  ordermanagement:
    email: dataservice@dzhw.eu
  projectmanagement:
    email: datadeposit@dzhw.eu
  server:
    instance-index: ${cf.instance.index}
    context-root: https://metadata.fdz.dzhw.eu
  elasticsearch-client:
    url: ${vcap.services.elastic.credentials.sslUri}
    read-timeout: 60000
  elasticsearch-angular-client:
    apiVersion: '7.3'
    logLevel: error
    pageSize: 10
  dara:
    endpoint: ${vcap.services.dara.credentials.endpoint}
    username: ${vcap.services.dara.credentials.username}
    password: ${vcap.services.dara.credentials.password}
  rabbitmq:
    uri: ${vcap.services.rabbitmq.credentials.uri}
  websockets:
    allowed-origins:
      - https://metadata.fdz.dzhw.eu
  dataset-report-task:
    task-definition: dataset-report-task-prod
    cluster-name: metadatamanagement-prod
